services:
  spotlight-storage:
    build: .
    image: spotlight-storage:dev
    environment:
      - TRANSLATIONS_DIR=/app/static/translations
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
      - ./static/translations:/app/static/translations:ro